// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqDHRPhBn3N_thojBEwS0Ampruk40OOM',
    appId: '1:628093692667:web:2d9dc3f70d3ab4fc049e5e',
    messagingSenderId: '628093692667',
    projectId: 'ditonton-dicoding-expert',
    authDomain: 'ditonton-dicoding-expert.firebaseapp.com',
    storageBucket: 'ditonton-dicoding-expert.appspot.com',
    measurementId: 'G-2CPJ5NDMLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7rkGCmqY9tmyFjkt9hBZrvNgOzqr2Kn8',
    appId: '1:628093692667:android:ade1d11b9f746ad7049e5e',
    messagingSenderId: '628093692667',
    projectId: 'ditonton-dicoding-expert',
    storageBucket: 'ditonton-dicoding-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0M3WskDO4sxsm8eGbrZzzsQOu0CREmNs',
    appId: '1:628093692667:ios:674e177ba2ed5a91049e5e',
    messagingSenderId: '628093692667',
    projectId: 'ditonton-dicoding-expert',
    storageBucket: 'ditonton-dicoding-expert.appspot.com',
    iosClientId: '628093692667-mg6ie85vqu8dubg4gcg6svib28hf7t3r.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
